services:
  postgres:
    container_name: ai_resume_parser_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring_ai_resume
      PGDATA: /var/lib/postgresql/data/pgdata2
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: