spring:
  application:
    name: AI Resume Parser
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# these properties need to be well organized across the different ENV
app:
  security:
    jwt:
      access-token-expiration: 86400000 #24 hours for local testing #900000 # 15 minutes
      refresh-token-expiration: 604800000 # 7 days